(define (cube x)
  (* x x x))
(define (sum term a next b)
  (if (> a b)
      0
      (+ (term a)
         (sum term (next a) next b))))
(define (integral f a b dx)
  (define (add-dx x) (+ x dx))
  (* (sum f (+ a (/ dx 2.0)) add-dx b)
     dx))
(define (inc x)
  (+ x 1))
(define (simpson-rule f a b n)
  (define (h)
    (/ (- b a) n))
  (define (y k)
    (define (coeff x)
      (cond ((= x 0) 1)
            ((= x n) 1)
            ((= (remainder x 2) 0) 2)
            (else 4)))
    (* (coeff k) (f (+ a (* k (h))))))
  (* (/ (h) 3.0) (sum y 0 inc n)))