(define (compose f g)
  (lambda (x)
    (f (g x))))
(define (repeated f n)
  (lambda (x)
    (define (recr n)
      (if (= n 1)
          (f x)
          (f (recr (- n 1)))))
    (recr n)))
(define (repeated-compose f n)
  (if (= n 1)
      f
      (compose f (repeated-compose f (- n 1)))))
(define (square x)
  (* x x))
(define (inc x)
  (+ x 1))
(define dx 0.00001)
(define (smooth f)
  (lambda (x)
    (/ (+ (f (- x dx)) (f x) (f (+ x dx))) 3.0)))
(define (n-fold-smooth f n)
  (repeated f n))