(define (accumulate op initial sequence)
  (if (null? sequence)
      initial
      (op (car sequence)
          (accumulate op initial (cdr sequence)))))
(define (filter predicate sequence)
  (cond ((null? sequence) nil)
        ((predicate (car sequence))
         (cons (car sequence)
               (filter predicate (cdr sequence))))
        (else (filter predicate (cdr sequence)))))
(define (enumerate-interval low high)
  (if (> low high)
      nil
      (cons low (enumerate-interval (+ low 1) high))))
(define (flatmap proc seq)
  (accumulate append nil (map proc seq)))
(define (unique-pairs n)
  (flatmap
   (lambda (i)
     (map (lambda (j) (list j i))
          (enumerate-interval 1 (- i 1))))
   (enumerate-interval 1 n)))
(define (unique-triples n)
  (flatmap
   (lambda (i)
     (map (lambda (j) (cons j i))
          (enumerate-interval 1 (- (car i) 1))))   
   (unique-pairs n)))
(define (fold-left op initial sequence)
  (define (iter result rest)
    (if (null? rest)
        result
        (iter (op result (car rest))
              (cdr rest))))
  (iter initial sequence))
(define (triple-sum triple)    
  (fold-left + 0 triple))
(define (triples-with-equal-sum n s)
  (define (sum-equal-to-s? triple)
    (= s (triple-sum triple)))
  (filter sum-equal-to-s? (unique-triples n)))