(define (make-interval x y)
  (cons x y))
(define (lower-bound i)
  (car i))
(define (upper-bound i)
  (cdr i))
(define (make-center-percent c percent)
  (make-interval (* c (- 1 (/ percent 100))) (* c (+ 1 (/ percent 100)))))
(define (percent interval)
  (* 100 (/ (abs (- (center interval) (lower-bound interval))) (center interval))))
(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))