(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (average a b)
  (/ (+ a b) 2.0))
(define (midpoint-segment segment)
  (define (average-point point-selector segment)
    (average (point-selector (start-segment segment)) (point-selector (end-segment segment))))
  (define (average-x segment)    
    (average-point x-point segment))
  (define (average-y segment)
    (average-point y-point segment))
  
  (make-point (average-x segment) (average-y segment)))
(define origin (make-point 0 0))
(define pointA (make-point 2 4))